### ISSUE TITLE
Passing environment variable

### ISSUE THREAD

**Issue by BecomeWeasel** [jayef0/chalice-extended-action#8]
Hi.
Can I pass environment variable by defining variable in yaml file like this below?

```yaml
jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: chalice deploy
        uses: jayef0/chalice-extended-action@release-v0.2.1
        env:
          REQUIREMENTS_FILE: requirements.txt
          OPERATION: deploy
          STAGE: dev
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          MONGO_ADDRESS: ${{ secrets.MONGO_ADDRESS }}
          MONGO_USER: ${{ secrets.MONGO_USER }}
          MONGO_PWD: ${{ secrets.MONGO_PWD }}
          AWS_DEFAULT_REGION: ap-northeast-2
```

I tried, but didn't work.
